export interface INotificationItem {
    id: string
    title: string
    description: string
    image: string | null
    isReaded: boolean
    date: Date
}



export const MOCKS: INotificationItem[] = [
    {
        id: "6157ee7b-5a77-4270-b2cd-7a0a7f044ccc",
        title: "Do magna",
        description: "Consectetur adipiscing elit sed do eiusmod tempor. Ut enim ad minim veniam quis nostrud exercitation ullamco. Ut enim ad minim veniam quis nostrud exercitation ullamco.",
        image: "image.png",
        isReaded: true,
        date: new Date("2025-05-12T10:42:31.640109"),
    },
    {
        id: "bb9967cc-b183-4e99-9a4a-8f05659c1379",
        title: "Ipsum ipsum sit ut magna incididunt et lorem incididunt elit ipsum dolore incididunt",
        description: "Ut enim ad minim veniam quis nostrud exercitation ullamco. Laboris nisi ut aliquip ex ea commodo consequat. Incididunt ut labore et dolore magna aliqua.",
        image: null,
        isReaded: false,
        date: new Date("2024-08-20T18:55:31.641280"),
    },
    {
        id: "84d567d9-6438-45f3-93d2-b74baf37a52f",
        title: "Ipsum elit incididunt",
        description: "Laboris nisi ut aliquip ex ea commodo consequat.",
        image: null,
        isReaded: true,
        date: new Date("2025-01-25T06:23:31.641749"),
    },
    {
        id: "17e42815-2039-4699-a00f-8a5071538cc8",
        title: "Do dolor labore",
        description: "Ut enim ad minim veniam quis nostrud exercitation ullamco. Laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet. Incididunt ut labore et dolore magna aliqua. Laboris nisi ut aliquip ex ea commodo consequat.",
        image: "image.png",
        isReaded: true,
        date: new Date("2024-10-28T08:21:31.642290"),
    },
    {
        id: "c265fe32-22dd-4b40-ac0f-1d2390777cf3",
        title: "Dolor incididunt incididunt",
        description: "Incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco.",
        image: null,
        isReaded: true,
        date: new Date("2024-09-22T14:48:31.642672"),
    },
    {
        id: "d8e6287d-1297-4b1e-b3c1-e0a8c746fbe2",
        title: "Labore lorem dolor eiusmod dolor sit",
        description: "Consectetur adipiscing elit sed do eiusmod tempor.",
        image: "image.png",
        isReaded: false,
        date: new Date("2024-11-30T03:44:31.642822"),
    },
    {
        id: "521df206-81c6-4b44-ae6c-caae9ebc8384",
        title: "Amet aliqua ipsum consectetur consectetur elit sit sed",
        description: "Laboris nisi ut aliquip ex ea commodo consequat. Laboris nisi ut aliquip ex ea commodo consequat. Incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit sed do eiusmod tempor.",
        image: null,
        isReaded: false,
        date: new Date("2024-12-04T15:22:31.642958"),
    },
    {
        id: "ca8e8b91-3cf4-4ac7-b6e4-07489d3f8899",
        title: "Magna magna dolor elit sed",
        description: "Incididunt ut labore et dolore magna aliqua. Incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco. Consectetur adipiscing elit sed do eiusmod tempor. Ut enim ad minim veniam quis nostrud exercitation ullamco.",
        image: null,
        isReaded: true,
        date: new Date("2025-03-07T08:42:31.643831"),
    },
    {
        id: "7407bda8-6f25-430d-91ad-87f0a9f98211",
        title: "Et sit incididunt sit sed eiusmod consectetur sit et ipsum ipsum",
        description: "Laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam quis nostrud exercitation ullamco. Consectetur adipiscing elit sed do eiusmod tempor. Ut enim ad minim veniam quis nostrud exercitation ullamco. Laboris nisi ut aliquip ex ea commodo consequat.",
        image: "image.png",
        isReaded: false,
        date: new Date("2024-10-22T06:06:31.644191"),
    },
    {
        id: "e27f9794-98bc-45a5-a9b3-ca5b8daa6416",
        title: "Dolor amet et sed incididunt et dolore magna magna adipiscing elit lorem ipsum",
        description: "Consectetur adipiscing elit sed do eiusmod tempor. Consectetur adipiscing elit sed do eiusmod tempor.",
        image: null,
        isReaded: false,
        date: new Date("2024-11-28T10:35:31.645376"),
    },
    {
        id: "d7004844-02a6-4da7-8817-fe48aaf3aabe",
        title: "Sed ut eiusmod",
        description: "Incididunt ut labore et dolore magna aliqua. Laboris nisi ut aliquip ex ea commodo consequat. Consectetur adipiscing elit sed do eiusmod tempor. Consectetur adipiscing elit sed do eiusmod tempor.",
        image: null,
        isReaded: false,
        date: new Date("2024-10-31T08:31:31.645523"),
    },
    {
        id: "3774976b-bede-430d-b878-51e3ac5c0708",
        title: "Tempor aliqua consectetur consectetur incididunt lorem do incididunt ut amet labore tempor labore aliqua",
        description: "Ut enim ad minim veniam quis nostrud exercitation ullamco.",
        image: "image.png",
        isReaded: false,
        date: new Date("2024-12-24T06:24:31.645633"),
    },
    {
        id: "65d60d5f-1247-4829-8600-88be07b266a5",
        title: "Amet sed lorem adipiscing labore amet eiusmod",
        description: "Laboris nisi ut aliquip ex ea commodo consequat. Incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit sed do eiusmod tempor.",
        image: null,
        isReaded: false,
        date: new Date("2024-09-22T15:21:31.645814"),
    },
    {
        id: "7625ce54-6c19-4c06-b44a-c4717c7627f9",
        title: "Adipiscing amet ut",
        description: "Consectetur adipiscing elit sed do eiusmod tempor. Laboris nisi ut aliquip ex ea commodo consequat. Consectetur adipiscing elit sed do eiusmod tempor. Laboris nisi ut aliquip ex ea commodo consequat.",
        image: "image.png",
        isReaded: true,
        date: new Date("2025-06-02T06:51:31.645914"),
    },
    {
        id: "ebce019f-3a2a-420d-88cd-b4d73dbab134",
        title: "Adipiscing eiusmod dolore incididunt consectetur labore et dolor ut sit elit elit",
        description: "Consectetur adipiscing elit sed do eiusmod tempor. Laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet. Ut enim ad minim veniam quis nostrud exercitation ullamco. Laboris nisi ut aliquip ex ea commodo consequat.",
        image: "image.png",
        isReaded: true,
        date: new Date("2025-02-15T01:31:31.646104"),
    },
    {
        id: "a656f0a8-c090-4eef-bf8b-2bfd887e50bb",
        title: "Lorem et elit incididunt amet ut do lorem dolore amet lorem dolore do",
        description: "Ut enim ad minim veniam quis nostrud exercitation ullamco. Consectetur adipiscing elit sed do eiusmod tempor. Incididunt ut labore et dolore magna aliqua. Laboris nisi ut aliquip ex ea commodo consequat.",
        image: "image.png",
        isReaded: false,
        date: new Date("2025-01-05T18:41:31.646194"),
    },
    {
        id: "fd5ad7e9-7b68-48c0-9cf0-bb884edff6f9",
        title: "Ut sit labore incididunt dolor sit ipsum consectetur eiusmod lorem tempor magna",
        description: "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Consectetur adipiscing elit sed do eiusmod tempor. Laboris nisi ut aliquip ex ea commodo consequat.",
        image: "image.png",
        isReaded: true,
        date: new Date("2024-09-29T21:27:31.646256"),
    },
    {
        id: "aa245b17-86c5-4240-b224-5fb9236883bf",
        title: "Tempor sed incididunt tempor elit dolore",
        description: "Consectetur adipiscing elit sed do eiusmod tempor. Incididunt ut labore et dolore magna aliqua.",
        image: "image.png",
        isReaded: false,
        date: new Date("2025-01-27T00:19:31.646309"),
    },
    {
        id: "b94b3119-5184-485a-9223-89fccd98661e",
        title: "Amet magna dolor lorem et sit sit dolore amet et tempor",
        description: "Incididunt ut labore et dolore magna aliqua. Laboris nisi ut aliquip ex ea commodo consequat.",
        image: "image.png",
        isReaded: true,
        date: new Date("2025-07-11T02:02:31.646363"),
    },
    {
        id: "eed1b0f7-a491-439d-b80b-445c2e807d43",
        title: "Labore ut do et",
        description: "Laboris nisi ut aliquip ex ea commodo consequat. Incididunt ut labore et dolore magna aliqua.",
        image: null,
        isReaded: true,
        date: new Date("2024-08-23T13:11:31.646412"),
    },
    {
        id: "c10255be-63bd-4f3b-9d8a-024e10d3ed64",
        title: "Tempor ut lorem amet lorem do sit dolore dolore elit consectetur et",
        description: "Incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet. Consectetur adipiscing elit sed do eiusmod tempor. Laboris nisi ut aliquip ex ea commodo consequat.",
        image: "image.png",
        isReaded: false,
        date: new Date("2025-03-11T13:03:31.646486"),
    },
    {
        id: "3d6f1589-4409-4b4c-85a2-50105b5f5f72",
        title: "Dolore et labore ipsum ut sit et ut magna",
        description: "Consectetur adipiscing elit sed do eiusmod tempor. Incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit sed do eiusmod tempor.",
        image: "image.png",
        isReaded: false,
        date: new Date("2024-12-31T09:22:31.646553"),
    },
    {
        id: "ca305e4d-2985-4ac1-8e9f-7d99c36e7528",
        title: "Magna sit elit ut",
        description: "Incididunt ut labore et dolore magna aliqua. Incididunt ut labore et dolore magna aliqua.",
        image: null,
        isReaded: true,
        date: new Date("2024-10-13T20:33:31.646592"),
    },
    {
        id: "2b81d07d-5601-4083-8dae-696ebaa02c17",
        title: "Consectetur dolor lorem tempor aliqua labore eiusmod labore consectetur elit ipsum do",
        description: "Laboris nisi ut aliquip ex ea commodo consequat.",
        image: "image.png",
        isReaded: false,
        date: new Date("2024-10-17T05:24:31.646617"),
    },
    {
        id: "d838cceb-0d70-42b1-afbe-c7fcfdc0da08",
        title: "Adipiscing adipiscing magna elit magna sed consectetur",
        description: "Incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Incididunt ut labore et dolore magna aliqua.",
        image: "image.png",
        isReaded: false,
        date: new Date("2025-03-21T11:33:31.646641"),
    },
    {
        id: "94c7fa8f-7ec8-44a1-beb2-fb97f86f687e",
        title: "Lorem do",
        description: "Consectetur adipiscing elit sed do eiusmod tempor. Laboris nisi ut aliquip ex ea commodo consequat. Consectetur adipiscing elit sed do eiusmod tempor. Consectetur adipiscing elit sed do eiusmod tempor.",
        image: null,
        isReaded: true,
        date: new Date("2024-09-29T17:23:31.646666"),
    },
    {
        id: "542b3fcc-89ba-4a60-a6d4-d29059661bb0",
        title: "Et sit ut magna dolor",
        description: "Lorem ipsum dolor sit amet.",
        image: null,
        isReaded: false,
        date: new Date("2024-10-03T10:29:31.646687"),
    },
    {
        id: "e006b6fb-392d-4cb5-a6ba-76e24d70060d",
        title: "Magna tempor do dolor elit elit ut lorem sit sed eiusmod incididunt ut eiusmod",
        description: "Lorem ipsum dolor sit amet. Consectetur adipiscing elit sed do eiusmod tempor. Ut enim ad minim veniam quis nostrud exercitation ullamco. Lorem ipsum dolor sit amet. Ut enim ad minim veniam quis nostrud exercitation ullamco.",
        image: null,
        isReaded: false,
        date: new Date("2024-11-17T17:59:31.646710"),
    },
    {
        id: "58e7d4e3-93f0-44a3-a163-fb68881d6da3",
        title: "Incididunt sed lorem sed ipsum amet sit labore elit magna incididunt dolor incididunt",
        description: "Lorem ipsum dolor sit amet.",
        image: "image.png",
        isReaded: false,
        date: new Date("2024-08-14T08:46:31.646734"),
    },
    {
        id: "f8028127-5296-46de-a4a3-a13bad917702",
        title: "Lorem magna lorem consectetur dolor incididunt ut incididunt do amet dolore eiusmod",
        description: "Ut enim ad minim veniam quis nostrud exercitation ullamco. Laboris nisi ut aliquip ex ea commodo consequat.",
        image: null,
        isReaded: true,
        date: new Date("2024-12-01T16:21:31.646762"),
    },
    {
        id: "18149b77-11d2-46a4-963c-96055fec82e4",
        title: "Incididunt adipiscing consectetur",
        description: "Lorem ipsum dolor sit amet. Ut enim ad minim veniam quis nostrud exercitation ullamco. Consectetur adipiscing elit sed do eiusmod tempor.",
        image: "image.png",
        isReaded: false,
        date: new Date("2024-09-17T20:48:31.646784"),
    },
    {
        id: "960304dd-fe5c-4c6a-815f-4b2686a79781",
        title: "Sed consectetur labore labore amet do aliqua incididunt aliqua dolore do",
        description: "Incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet. Laboris nisi ut aliquip ex ea commodo consequat.",
        image: "image.png",
        isReaded: false,
        date: new Date("2025-06-17T16:17:31.646823"),
    },
    {
        id: "61e478f8-26f8-4e38-9ed9-c960007a9bf5",
        title: "Tempor et eiusmod lorem elit adipiscing ipsum aliqua elit dolore",
        description: "Ut enim ad minim veniam quis nostrud exercitation ullamco. Ut enim ad minim veniam quis nostrud exercitation ullamco.",
        image: "image.png",
        isReaded: true,
        date: new Date("2025-02-21T19:35:31.646846"),
    },
    {
        id: "0181e8c5-6bfe-4db6-9f8f-b9e281445a5f",
        title: "Magna sit sit sed adipiscing adipiscing do sit dolore eiusmod eiusmod magna adipiscing amet consectetur",
        description: "Incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit sed do eiusmod tempor. Ut enim ad minim veniam quis nostrud exercitation ullamco. Lorem ipsum dolor sit amet. Laboris nisi ut aliquip ex ea commodo consequat.",
        image: null,
        isReaded: true,
        date: new Date("2025-07-15T11:16:31.646873"),
    },
    {
        id: "ba4614b0-da4a-4229-a0c2-b2af50f9a715",
        title: "Adipiscing labore et sit aliqua amet amet magna tempor labore adipiscing",
        description: "Ut enim ad minim veniam quis nostrud exercitation ullamco. Consectetur adipiscing elit sed do eiusmod tempor.",
        image: "image.png",
        isReaded: true,
        date: new Date("2025-05-07T07:13:31.646907"),
    },
    {
        id: "bdf06fd9-0fad-471b-b78d-9f32555a044d",
        title: "Elit adipiscing elit et sit ipsum ut elit aliqua eiusmod",
        description: "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Incididunt ut labore et dolore magna aliqua. Incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit sed do eiusmod tempor.",
        image: null,
        isReaded: true,
        date: new Date("2024-09-14T18:47:31.646931"),
    },
    {
        id: "76c59e54-5bfd-413d-b70b-ac3044e8445c",
        title: "Tempor aliqua sed ipsum et amet consectetur et amet do consectetur",
        description: "Incididunt ut labore et dolore magna aliqua.",
        image: "image.png",
        isReaded: false,
        date: new Date("2025-05-24T19:00:31.646976"),
    },
    {
        id: "4001e11f-016f-43f4-b6d9-1699e4ad13fe",
        title: "Do tempor consectetur tempor ipsum adipiscing consectetur et lorem lorem do lorem magna eiusmod sit",
        description: "Ut enim ad minim veniam quis nostrud exercitation ullamco.",
        image: "image.png",
        isReaded: false,
        date: new Date("2024-08-08T22:56:31.647000"),
    },
    {
        id: "766b8b5b-6866-4584-b0bb-437d5601438f",
        title: "Dolor consectetur ut magna amet sed",
        description: "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet.",
        image: null,
        isReaded: true,
        date: new Date("2024-10-10T04:59:31.647022"),
    },
    {
        id: "98ef4178-76fc-4b26-858a-65e787043224",
        title: "Aliqua et sed sit do sit adipiscing elit dolore",
        description: "Ut enim ad minim veniam quis nostrud exercitation ullamco.",
        image: "image.png",
        isReaded: true,
        date: new Date("2024-11-11T08:09:31.647043"),
    },
    {
        id: "fc2b4e2e-6b6b-490e-830d-b02141f97ae1",
        title: "Lorem et lorem magna eiusmod labore aliqua aliqua ipsum adipiscing ipsum adipiscing ipsum lorem magna",
        description: "Ut enim ad minim veniam quis nostrud exercitation ullamco.",
        image: "image.png",
        isReaded: false,
        date: new Date("2025-03-25T20:47:31.647066"),
    },
    {
        id: "5fb30ce2-9a32-4f81-a2b6-d529dc33c3bb",
        title: "Sit do lorem sit lorem adipiscing sed aliqua dolor tempor sed amet eiusmod sed",
        description: "Incididunt ut labore et dolore magna aliqua.",
        image: "image.png",
        isReaded: true,
        date: new Date("2025-07-01T15:08:31.647091"),
    },
    {
        id: "17a9e21d-77b1-420b-8b89-2b7cbdd2c5fa",
        title: "Aliqua ipsum dolore amet sit aliqua",
        description: "Incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit sed do eiusmod tempor. Laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam quis nostrud exercitation ullamco.",
        image: null,
        isReaded: false,
        date: new Date("2025-02-21T12:50:31.647113"),
    },
    {
        id: "27df96f5-28b2-4fe4-a696-e06a8f3dfcc3",
        title: "Eiusmod elit magna labore ut dolor dolor amet eiusmod adipiscing",
        description: "Incididunt ut labore et dolore magna aliqua. Incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit sed do eiusmod tempor. Incididunt ut labore et dolore magna aliqua.",
        image: "image.png",
        isReaded: true,
        date: new Date("2025-02-17T23:19:31.647136"),
    },
    {
        id: "0c4b0b24-6728-4ebd-8911-7c722bc32be6",
        title: "Et sit tempor magna aliqua",
        description: "Laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet. Ut enim ad minim veniam quis nostrud exercitation ullamco.",
        image: null,
        isReaded: false,
        date: new Date("2024-09-04T11:04:31.647186"),
    },
    {
        id: "04cb7e89-f4f6-4e8f-80cb-b6c2fec17341",
        title: "Tempor dolor",
        description: "Laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet.",
        image: null,
        isReaded: false,
        date: new Date("2024-09-17T19:10:31.647208"),
    },
    {
        id: "e97f81b6-002d-4f37-842d-e962944145cb",
        title: "Ipsum et consectetur adipiscing adipiscing elit ipsum aliqua adipiscing",
        description: "Ut enim ad minim veniam quis nostrud exercitation ullamco. Laboris nisi ut aliquip ex ea commodo consequat. Consectetur adipiscing elit sed do eiusmod tempor. Lorem ipsum dolor sit amet.",
        image: null,
        isReaded: false,
        date: new Date("2025-02-28T18:39:31.647231"),
    },
    {
        id: "08c60f0d-19e8-4f3d-97e5-ddd131112cff",
        title: "Sed sed amet incididunt consectetur consectetur elit sed sed incididunt do",
        description: "Consectetur adipiscing elit sed do eiusmod tempor. Ut enim ad minim veniam quis nostrud exercitation ullamco. Consectetur adipiscing elit sed do eiusmod tempor.",
        image: null,
        isReaded: true,
        date: new Date("2025-03-20T16:17:31.647267"),
    },
    {
        id: "622760ad-316b-41b7-a9cb-9fab0c4c059d",
        title: "Incididunt elit tempor tempor lorem incididunt amet aliqua et",
        description: "Laboris nisi ut aliquip ex ea commodo consequat. Laboris nisi ut aliquip ex ea commodo consequat. Consectetur adipiscing elit sed do eiusmod tempor.",
        image: null,
        isReaded: true,
        date: new Date("2025-04-07T22:18:31.647338"),
    },
    {
        id: "cf2c6860-7ff3-49c6-b0b1-e069aafcff32",
        title: "Aliqua dolor consectetur tempor labore tempor aliqua incididunt sed adipiscing tempor sed lorem et magna",
        description: "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Incididunt ut labore et dolore magna aliqua. Laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam quis nostrud exercitation ullamco.",
        image: "image.png",
        isReaded: true,
        date: new Date("2025-02-14T08:39:31.647388"),
    },
];